
<<<<<<< HEAD
=======

>>>>>>> ff9388f678ff7572f1474c8001a6475b0a57672c
# postgreSql Database configuration


spring.datasource.url=jdbc:postgresql://dpg-daria2t9fdbs739nfiq0-a.singapore-postgres.render.com:5432/billing_app_3k8w
spring.datasource.username=billing_app_3k8w_user
spring.datasource.password=2JkVBxM8v3fqvhJ883fKCntJL1Orru9p
#spring.datasource.url=${JDBC_POSTGRE_DATABASE_URL}
#spring.datasource.username=${DB_POSTGRE_USERNAME}
#spring.datasource.password=${DB_POSTGRE_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
